//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPage.refForXML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="refForXML.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findNearestStore", ReplyAction="http://tempuri.org/IService1/findNearestStoreResponse")]
        string findNearestStore(string zipCode, string storeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findNearestStore", ReplyAction="http://tempuri.org/IService1/findNearestStoreResponse")]
        System.Threading.Tasks.Task<string> findNearestStoreAsync(string zipCode, string storeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllStates", ReplyAction="http://tempuri.org/IService1/showAllStatesResponse")]
        string showAllStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllStates", ReplyAction="http://tempuri.org/IService1/showAllStatesResponse")]
        System.Threading.Tasks.Task<string> showAllStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTax", ReplyAction="http://tempuri.org/IService1/getTaxResponse")]
        string getTax(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTax", ReplyAction="http://tempuri.org/IService1/getTaxResponse")]
        System.Threading.Tasks.Task<string> getTaxAsync(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAirQuality", ReplyAction="http://tempuri.org/IService1/getAirQualityResponse")]
        string getAirQuality(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAirQuality", ReplyAction="http://tempuri.org/IService1/getAirQualityResponse")]
        System.Threading.Tasks.Task<string> getAirQualityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromMemberXML", ReplyAction="http://tempuri.org/IService1/removeFromMemberXMLResponse")]
        string removeFromMemberXML(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromMemberXML", ReplyAction="http://tempuri.org/IService1/removeFromMemberXMLResponse")]
        System.Threading.Tasks.Task<string> removeFromMemberXMLAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromStaffXML", ReplyAction="http://tempuri.org/IService1/removeFromStaffXMLResponse")]
        string removeFromStaffXML(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromStaffXML", ReplyAction="http://tempuri.org/IService1/removeFromStaffXMLResponse")]
        System.Threading.Tasks.Task<string> removeFromStaffXMLAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchMemberUsernameXML", ReplyAction="http://tempuri.org/IService1/searchMemberUsernameXMLResponse")]
        string searchMemberUsernameXML(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchMemberUsernameXML", ReplyAction="http://tempuri.org/IService1/searchMemberUsernameXMLResponse")]
        System.Threading.Tasks.Task<string> searchMemberUsernameXMLAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchMemberPasswordXML", ReplyAction="http://tempuri.org/IService1/searchMemberPasswordXMLResponse")]
        string searchMemberPasswordXML(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchMemberPasswordXML", ReplyAction="http://tempuri.org/IService1/searchMemberPasswordXMLResponse")]
        System.Threading.Tasks.Task<string> searchMemberPasswordXMLAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchStaffUsernameXML", ReplyAction="http://tempuri.org/IService1/searchStaffUsernameXMLResponse")]
        string searchStaffUsernameXML(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchStaffUsernameXML", ReplyAction="http://tempuri.org/IService1/searchStaffUsernameXMLResponse")]
        System.Threading.Tasks.Task<string> searchStaffUsernameXMLAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchStaffPasswordXML", ReplyAction="http://tempuri.org/IService1/searchStaffPasswordXMLResponse")]
        string searchStaffPasswordXML(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchStaffPasswordXML", ReplyAction="http://tempuri.org/IService1/searchStaffPasswordXMLResponse")]
        System.Threading.Tasks.Task<string> searchStaffPasswordXMLAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPage.refForXML.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPage.refForXML.IService1>, TryItPage.refForXML.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string findNearestStore(string zipCode, string storeName) {
            return base.Channel.findNearestStore(zipCode, storeName);
        }
        
        public System.Threading.Tasks.Task<string> findNearestStoreAsync(string zipCode, string storeName) {
            return base.Channel.findNearestStoreAsync(zipCode, storeName);
        }
        
        public string showAllStates() {
            return base.Channel.showAllStates();
        }
        
        public System.Threading.Tasks.Task<string> showAllStatesAsync() {
            return base.Channel.showAllStatesAsync();
        }
        
        public string getTax(string zipcode) {
            return base.Channel.getTax(zipcode);
        }
        
        public System.Threading.Tasks.Task<string> getTaxAsync(string zipcode) {
            return base.Channel.getTaxAsync(zipcode);
        }
        
        public string getAirQuality(string city) {
            return base.Channel.getAirQuality(city);
        }
        
        public System.Threading.Tasks.Task<string> getAirQualityAsync(string city) {
            return base.Channel.getAirQualityAsync(city);
        }
        
        public string removeFromMemberXML(string username) {
            return base.Channel.removeFromMemberXML(username);
        }
        
        public System.Threading.Tasks.Task<string> removeFromMemberXMLAsync(string username) {
            return base.Channel.removeFromMemberXMLAsync(username);
        }
        
        public string removeFromStaffXML(string username) {
            return base.Channel.removeFromStaffXML(username);
        }
        
        public System.Threading.Tasks.Task<string> removeFromStaffXMLAsync(string username) {
            return base.Channel.removeFromStaffXMLAsync(username);
        }
        
        public string searchMemberUsernameXML(string username) {
            return base.Channel.searchMemberUsernameXML(username);
        }
        
        public System.Threading.Tasks.Task<string> searchMemberUsernameXMLAsync(string username) {
            return base.Channel.searchMemberUsernameXMLAsync(username);
        }
        
        public string searchMemberPasswordXML(string username) {
            return base.Channel.searchMemberPasswordXML(username);
        }
        
        public System.Threading.Tasks.Task<string> searchMemberPasswordXMLAsync(string username) {
            return base.Channel.searchMemberPasswordXMLAsync(username);
        }
        
        public string searchStaffUsernameXML(string username) {
            return base.Channel.searchStaffUsernameXML(username);
        }
        
        public System.Threading.Tasks.Task<string> searchStaffUsernameXMLAsync(string username) {
            return base.Channel.searchStaffUsernameXMLAsync(username);
        }
        
        public string searchStaffPasswordXML(string username) {
            return base.Channel.searchStaffPasswordXML(username);
        }
        
        public System.Threading.Tasks.Task<string> searchStaffPasswordXMLAsync(string username) {
            return base.Channel.searchStaffPasswordXMLAsync(username);
        }
    }
}
